### ISSUE TITLE
TypeError: Assignment to constant variable.

### ISSUE THREAD

**Issue by whchen8** [jaebradley/nba-cli#36]
``` zsh
TypeError: Assignment to constant variable.
    at .../.npm-packages/lib/node_modules/nba-scoreboard/src/translators/data/ScoreboardDataTranslator.js:76:28
    at Array.forEach (native)
    at Object.module.exports.translateGameData (.../.npm-packages/lib/node_modules/nba-scoreboard/src/translators/data/ScoreboardDataTranslator.js:73:36)
    at .../.npm-packages/lib/node_modules/nba-scoreboard/src/data/NbaDataClient.js:63:55
    at tryCatcher (.../.npm-packages/lib/node_modules/nba-scoreboard/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (.../.npm-packages/lib/node_modules/nba-scoreboard/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (.../.npm-packages/lib/node_modules/nba-scoreboard/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (.../.npm-packages/lib/node_modules/nba-scoreboard/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (.../.npm-packages/lib/node_modules/nba-scoreboard/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (.../.npm-packages/lib/node_modules/nba-scoreboard/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (.../.npm-packages/lib/node_modules/nba-scoreboard/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (.../.npm-packages/lib/node_modules/nba-scoreboard/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

**Comment by jaebradley** [comment]
what's the command you are trying to run?

**Comment by whchen8** [comment]
Only `nba games tomorrow` works properly. Error above occurs for all other cases.

npm is installed using homebrew on OSX, and nba-scoreboard is installed globally by `npm install -g nba-scoreboard`.

**Comment by whchen8** [comment]
<img width="1151" alt="screen shot 2016-05-11 at 14 00 32" src="https://cloud.githubusercontent.com/assets/3682917/15194663/46be5444-1781-11e6-8b7e-e1c1675c6275.png">

**Comment by jaebradley** [comment]
do you mind reinstalling and testing again?
